apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-k8s-demo
  namespace: devops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-k8s-demo

  template:
    metadata:
      labels:
        app: devops-k8s-demo

    spec:
      containers:
        - name: devops-k8s-demo
          image: IMAGE_PLACEHOLDER 
          env: 
          -name: APP_VERSION
          value: "1.0.0"    
          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20