apiVersion: v1
kind: Service

metadata:
  name: devops-k8s-demo
  namespace: devops-demo

spec:
  type: LoadBalancer

  selector:
    app: devops-k8s-demo

  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP